### ISSUE TITLE
ViewModels in Collections do not cascade change events

### ISSUE THREAD

**Issue by brandon-james105** [chris579/MvvmBlazor#19]
When there are two open windows, a collection with ViewModels in it does not trigger a StateHasChanged event on the sister window. On [this page](https://github.com/brandon-james105/BlazorPlanningPoker/blob/master/PlanningPoker/Pages/Sessions.razor#L35), try starting and/or ending a session and watch what happens in the second window.

**Comment by chris579** [comment]
Given your code example you can't expect any changes to be reflected if you're not issuing any binding on the child view model. Every property you want to be updated when it changes needs a corresponding binding.

You have
```csharp
@foreach (var session in Bind(vm => vm.Sessions))
{
    <tr>
        <td><a href="sessions/@session.SessionId">@session.Title</a></td>
        <td>@session.State.ToString()</td>
        <td>
            <button class="btn btn-link" 
                    @onclick="@(() => BindingContext.RemoveSession(session.SessionId))">Delete</button>
            <button class="btn btn-link" 
                    @onclick="@(() => session.Start())"
                    disabled="@(session.State > Data.PlanningPokerSessionState.Lobby)">Start Session</button>
            <button class="btn btn-link" 
                    @onclick="@(() => session.End())"
                    disabled="@(session.State == Data.PlanningPokerSessionState.Complete)">End Session</button>
        </td>
    </tr>
}
```

changing your code to that
```csharp
@foreach (var session in Bind(vm => vm.Sessions))
{
    <tr>
        <td><a href="sessions/@session.SessionId">@session.Title</a></td>
        <td>@Bind(session, x => x.State)</td>
        <td>
            <button class="btn btn-link" 
                    @onclick="@(() => BindingContext.RemoveSession(session.SessionId))">Delete</button>
            <button class="btn btn-link" 
                    @onclick="@(() => session.Start())"
                    disabled="@(Bind(session, x => x.State) > Data.PlanningPokerSessionState.Lobby)">Start Session</button>
            <button class="btn btn-link" 
                    @onclick="@(() => session.End())"
                    disabled="@(Bind(session, x => x.State) == Data.PlanningPokerSessionState.Complete)">End Session</button>
        </td>
    </tr>
}
```
makes it work. A property will be monitored for changes if there is one binding issued. You could just make one binding and then use the property as you would normally but I would strongly suggest against that. It's error prone.

You will find out that you can't bind to your interface but you need to bind to your view model implementation directly. I was thinking if it would make sense to bind to an interface instead of an implementation but I decided that this isn't really how it's supposed to be. Maybe I could also allow types of `INotifyPropertyChanged` to be bound to but I don't see the point. You might want to clean up the way you're handling view models. You're directly passing your model data to your view model as an interface where it's implementation is a view model. You don't want to do that. You want to cleanly separate all 3 layers from each other. Entities/Model data needs to be wrapped or mapped by a view model and not be a view model directly. 

I will cover the topic of sub bindings especially for lists in the Readme soon to clarify it's usage.

**Comment by brandon-james105** [comment]
Thank you for the explanation. It was the implementation. I was able to fix it with your suggestion. I guess it escaped me. I would have done the same thing in a forms-based application. But it is really cool to see this work serverside instead of the client. I can't wait for the client to officially come out next year!

**Comment by chris579** [comment]
Same for me. Really curious how that's working out. Although the server implementation is really good and makes developing a bit faster that the classical client/server approach.

**Comment by brandon-james105** [comment]
I have this scenario in mind where I want an offline device to have UI, which would be basically the same interface that is on the serverside. I would like some dynamic plugins on an offline UI. The user could register their offline device with the serverside UI, then the offline UI, while online, could download the plugins for use with an web service and store them for use if it ever goes offline. I had been investigating technology capable of doing that but none of them have been as smooth as what I think Blazor could offer.

**Comment by chris579** [comment]
Yeah, sure. There are many scenarios for client side applications. PWA is getting interesting with .NET 5 and also Blazor Native. Plus, the electron like approach enables to write cross platform desktop applications. The simple fact that I don't need to write javascript any more makes me happy enough tbh.

**Comment by brandon-james105** [comment]
I'm there with you. I feel like JavaScript and SPAs were kind of just a shoehorn because the nature of the web browser and it makes creating a great web experience so much more expensive to build. WebAssembly, to me, really is the future. In the past I think people thought that Java with the JVM was going to be the way, but we all see how that has gone. I'm not pleased with it. Mobile phones really picked up, and became a platform Java didn't work on. Mobile kind of fragmented the developer base. Developers were then building native apps for these additional platforms and that didn't really progress things much. Now that there are multiple platforms to develop for, there needed to be a cheaper, easier way to develop for any new platform. Web browsers were on every platform, and the way I see it, the web browser is effectively a virtual machine, or just some overhead for an application to run. Electron was born from a headless Chromium instance. It sort of does some of that. Electron installs a Chromium runtime (think C++ redists of today) and use so much RAM. I think the case for creating a native app for a platform is going down more and more. I guess I'm a little biased because I started on the web. I have been meaning to branch out but it's just not really that viable. I am creating a Xamarin app that uses Bluetooth but that's the closest I'm getting to not using web technologies at the moment. I'm reading that in the future even web browsers could all do Bluetooth, too!

**Comment by chris579** [comment]
Actually I'm coming from the exact opposite direction as I started with C# (and also got back to it quite soon) and never really had any touching points with js until I started looking into web development (fortunately with Angular) and started tearing out my hear because of this js specialty and this one and 400 MB of node modules and then this js stuff acts totally different in FF than in Chrome and so on. Letting js behind with WebAssembly is not only the future but the only reasonable step as the js world is cluttered with shit on every side of the road. Plus, for me a language that has no static types and proper type safety is not worth using for a program with more complexity than just a script. There are way too many problems with not type safe languages I faced in my (rather short) developer experience, so I sticked to C# again and love the way how Microsoft shifts to a modern and open platform.

**Comment by brandon-james105** [comment]
The node modules thing really sinks me as a web developer. I've heard plenty of bad things about potential vulnerabilities from Node packages. And most of the time the Node dev dependencies are pretty much just compensating for the fact that IDEs are not great at debugging web apps. But yeah you're right, I almost forgot early days of web dev was using jQuery because of browser incompatibilities. That was really bad. Just like with all these weighty apps you have to download for all these different companies. You have to download an entire client with Angular version A but even though website B uses a slightly different version, your client has to re-download it as they're usually packaged in a minified version. The cache on a typical web browser today is probably so abused by the modern web. The web is very fragmented. People don't like to talk about that because of how arbitrarily fragmented it is. It's the wild west on the web still. It's even more fragmented than devs like to say Android is. But yeah, C# is great. It's awesome Microsoft has Nadella leading right now. His developer mind I think is really impacting us right now. It's a shame their Windows Mobile platform isn't pervasive today. I think I could see an alternate Windows coming out before long, with the legacy part of Windows being stripped out, the way that native apps are becoming less and less relevant. That Surface Neo is looking good.

**Comment by chris579** [comment]
As promised, I extended the samples to cover this topic and also clean them up a bit.
