### ISSUE TITLE
IDisposable not working

### ISSUE THREAD

**Issue by pigwing** [chris579/MvvmBlazor#35]
when i leave page,ViewModelBase dispose method not trigger and 
![image](https://user-images.githubusercontent.com/8393545/89398012-27e01900-d743-11ea-8881-6826480c2fa3.png)
is working

**Comment by pigwing** [comment]
![image](https://user-images.githubusercontent.com/8393545/89398138-4e05b900-d743-11ea-8426-0a3452ea781c.png)
that is working

**Comment by pigwing** [comment]
i found 
@inherits MvvmComponentBase<ClockViewModel> is not working
and the
@inherits MvvmComponentBase
@inject ClockViewModel ClockViewModel
is working

**Comment by chris579** [comment]
MvvmComponentBase is implementing `IDisposable`. If you want to dispose something in your component (no clue why you would do that) you need to override the virtual `Dispose(bool)` method. Make sure to call the base implementation, otherwise you will leak binding resources.

See the [implementation](https://github.com/chris579/MvvmBlazor/blob/master/src/MvvmBlazor/Components/MvvmComponentBase.cs#L105) for reference.
